baseURL: https://honuli.com/
languageCode: en-us
title: Honuli
theme: "PaperMod"

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
googleAnalytics: G-3EB29D9GT5

disableKinds: [ "term", "taxonomy", "sitemap" ]

minify:
  disableXML: true
  minifyOutput: true

params:
  title: Honuli Books
  description: "Honuli - Book Creator for Children"
  keywords: [ "Book", "Children", "French", "Francais", "Book Creator for Children", "Honuli" ]
  author: Honuli Books
  DateFormat: "January 1, 2023"
  defaultTheme: auto # dark, light
  disableThemeToggle: false
  env: production  # To enable Google Analytics

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: false
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: false
  disableSpecial1stPost: true
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: true
  showtoc: false
  tocopen: false

  assets:
    favicon: "./favicon.png"
    favicon16x16: "./favicon.png"
    favicon32x32: "./favicon.png"
    apple_touch_icon: "./favicon.png"
    safari_pinned_tab: "./favicon.png"

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Honuli Books
    subtitle: Book Creator for Children
    imageUrl: "./logo.png"
    imageWidth: 260
    imageHeight: 260
    imageTitle: Honuli - Book Creator for Children

  socialIcons:
    - name: email
      url: "mailto:kaulana.honu@gmail.com"
    - name: twitter
      url: "https://twitter.com/honu_li"

  analytics:
    google:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: books
      name: books
      url: books
      weight: 10
    - identifier: about
      name: about
      url: about
      weight: 20

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
server:
  headers:
    - for: "/*"
      values:
        Content-Security-Policy: "default-src 'self' 'unsafe-eval' 'unsafe-inline' www.google-analytics.com avatars.githubusercontent.com;"
        Access-Control-Allow-Origin: 'http://honuli.com'
        X-Frame-Options: "DENY"
        X-XSS-Protection: "1; mode=block"
        X-Content-Type-Options: "nosniff"
        Referrer-Policy: "strict-origin-when-cross-origin"
        Strict-Transport-Security: "max-age=2592000; includeSubDomains; preload"